name: tapps
favicon: null
layout_spectrum: 0.9500174182467163
typography_spectrum: 0.447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
